name: flutter_web_temple_map
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  flutter_riverpod: ^2.6.1
  hooks_riverpod:  ^2.6.1
  riverpod_annotation: ^2.3.0
  freezed_annotation: ^2.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.8
  riverpod_generator: ^2.3.0
  freezed: ^2.4.7

flutter:

  uses-material-design: true
